/*

 * @Nombre    : AcercaDe
 * @Author    : Erick Rodriguez
 * @Copyright : Erick Rodriguez
 * @Creado el : 09-mar-2019, 12:50:37 AM
 */
package envio_comprobantes_amdc;

import java.awt.Color;

/**
 *
 * @author Erick R. Rodríguez
 */
public class AcercaDe extends javax.swing.JFrame {

    javax.swing.JFrame _p;
    /**
     * Creates new form AcercaDe
     */
    public AcercaDe(javax.swing.JFrame padre) {
        //initComponents();
        _p = padre;
        //Visual_frame es el nombre del JFrame principal
        AcercaDe.this.setUndecorated(true);
        initComponents();
        //Con esto hacemos que el JFrame no se vea 
        //Sino puedes quitarlo.
        AcercaDe.this.setBackground(new Color(0,0,0,0));
        //Con esto le damos tranparencia a los objetos que tiene el JFrame
        //Tambien al JFrame, desde 0.0f a 1.0f 
        AcercaDe.this.setOpacity(0.94f);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgAcercaDe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        imgAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Acerca_de_v221.png"))); // NOI18N
        imgAcercaDe.setOpaque(true);
        imgAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgAcercaDeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgAcercaDe)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgAcercaDe)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgAcercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgAcercaDeMouseClicked
        // TODO add your handling code here:
        _p.setEnabled(true);
        dispose();
    }//GEN-LAST:event_imgAcercaDeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcercaDe(new javax.swing.JFrame()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgAcercaDe;
    // End of variables declaration//GEN-END:variables
}
