/*

 * @Nombre    : ConfiguracionInterna
 * @Author    : Erick Rodriguez
 * @Copyright : Erick Rodriguez
 * @Creado el : 08-mar-2019, 02:50:44 PM
 */
package envio_comprobantes_amdc;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick R. Rodríguez
 */
public class ConfiguracionInterna extends javax.swing.JDialog {

    /**
     * Creates new form ConfiguracionInterna
     */
    public ConfiguracionInterna(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        recuperarInformacion();
        
        

        btnGuardarDB.setIcon(new ImageIcon("src/imagenes/diskette_save_saveas_1514.png"));
        btnProbarDB.setIcon(new ImageIcon("src/imagenes/probar_db.png"));
        btnSalirCnf.setIcon(new ImageIcon("src/imagenes/salir-de-mi-perfil-icono-3964-32.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnProbarDB = new javax.swing.JButton();
        txtURL = new javax.swing.JTextField();
        btnSalirCnf = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPuerto = new javax.swing.JTextField();
        txtUrlLogoIzq = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBaseDatos = new javax.swing.JTextField();
        txtUrlLogoDer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtPane_logos = new javax.swing.JTextPane();
        txtUsuarioDB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPassDB = new javax.swing.JPasswordField();
        btnGuardarDB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRecargarConfigInterna = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("URL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 332, -1, -1));

        btnProbarDB.setText("Probar DB");
        btnProbarDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProbarDBActionPerformed(evt);
            }
        });
        getContentPane().add(btnProbarDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 529, 130, -1));
        getContentPane().add(txtURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 329, 261, -1));

        btnSalirCnf.setText("Salir");
        btnSalirCnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirCnfActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirCnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 529, 98, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Puerto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("URL Logo Izq.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        getContentPane().add(txtPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 367, 261, -1));

        txtUrlLogoIzq.setToolTipText("");
        txtUrlLogoIzq.setMaximumSize(new java.awt.Dimension(6, 20));
        txtUrlLogoIzq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUrlLogoIzqKeyTyped(evt);
            }
        });
        getContentPane().add(txtUrlLogoIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 58, 261, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Base de Datos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 411, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("URL Logo Der.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 92, -1, -1));
        getContentPane().add(txtBaseDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 405, 261, -1));

        txtUrlLogoDer.setMaximumSize(new java.awt.Dimension(6, 20));
        txtUrlLogoDer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUrlLogoDerKeyTyped(evt);
            }
        });
        getContentPane().add(txtUrlLogoDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 89, 261, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("usuario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 446, -1, -1));

        jScrollPane1.setViewportView(jTxtPane_logos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 135, 460, 188));
        getContentPane().add(txtUsuarioDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 443, 261, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Contraseña");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 484, -1, -1));

        jLabel9.setText("Muestra");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 115, -1, -1));
        getContentPane().add(txtPassDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 481, 261, -1));

        btnGuardarDB.setText("Guardar");
        btnGuardarDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDBActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 529, 122, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Configuración");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 466, -1));

        btnRecargarConfigInterna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/recargar_img.png"))); // NOI18N
        btnRecargarConfigInterna.setToolTipText("Recargar URLs de logos por defecto.");
        btnRecargarConfigInterna.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecargarConfigInterna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecargarConfigInternaMouseClicked(evt);
            }
        });
        getContentPane().add(btnRecargarConfigInterna, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProbarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProbarDBActionPerformed
        // TODO add your handling code here:
        Con_DB db = new Con_DB();
        String urlDB = txtURL.getText().trim();
        String puertoDB = txtPuerto.getText().trim();
        String nombreDB = txtBaseDatos.getText().trim();
        String usuarioDB = txtUsuarioDB.getText().trim();
        char[] passDB_array = txtPassDB.getPassword();
        
        String passDB = "";
        
        for(int i = 0; i < passDB_array.length; i++){
            passDB += passDB_array[i];
        }

        if (db.probarConexion(urlDB, puertoDB, nombreDB, usuarioDB, passDB)) {
            JOptionPane.showMessageDialog(null, "Conexión Exitosa!!!:", "PRUEBA DE CONEXIÓN",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnProbarDBActionPerformed

    private void btnSalirCnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirCnfActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirCnfActionPerformed

    private void txtUrlLogoIzqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUrlLogoIzqKeyTyped
        // TODO add your handling code here:
        this.mostrarPreview();
    }//GEN-LAST:event_txtUrlLogoIzqKeyTyped

    private void txtUrlLogoDerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUrlLogoDerKeyTyped
        // TODO add your handling code here:
        this.mostrarPreview();
    }//GEN-LAST:event_txtUrlLogoDerKeyTyped

    private void btnGuardarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDBActionPerformed
        // TODO add your handling code here:
        String urlLogoI = txtUrlLogoIzq.getText().trim();
        String urlLogoD = txtUrlLogoDer.getText().trim();
        String url = txtURL.getText().trim();
        String puerto = txtPuerto.getText().trim();
        String nombreDB = txtBaseDatos.getText().trim();
        String usuarioDB = txtUsuarioDB.getText().trim();
        char[] passDB_array = txtPassDB.getPassword();
        
        String passDB = "";
        
        for(int i = 0; i < passDB_array.length; i++){
            passDB += passDB_array[i];
        }
        
        if(urlLogoI.length() == 0){
            urlLogoI = "Vacio";
        }
        if(urlLogoD.length() == 0){
            urlLogoD = "Vacio";
        }

        if (urlLogoD.length() == 0 || urlLogoI.length() == 0 || url.length() == 0 || puerto.length() == 0 || nombreDB.length() == 0 || usuarioDB.length() == 0 || passDB.length() == 0) {
            JOptionPane.showMessageDialog(null, "Datos de configuración o datos de conexión a base de datos está incompleta", "ERROR",
                JOptionPane.ERROR_MESSAGE);
        } else {
            Con_DB db = new Con_DB();
            if (db.probarConexion(url, puerto, nombreDB, usuarioDB, passDB)) {
                String cadenaConf = url + "#&&#" + puerto + "#&&#" + nombreDB + "#&&#" + usuarioDB + "#&&#" + passDB + "#&&#" + urlLogoI + "#&&#" + urlLogoD;

                String ruta = "";
                File midir = new File(".");
                try {
                    ruta = midir.getCanonicalPath();

                } catch (IOException e) {
                }

                //Cifrar los datos
                TripleDes tDES = new TripleDes();
                String confCifrada = tDES.encriptar_txt_3DES(cadenaConf);

                String rutaArchivo = ruta + "\\src\\configuraciones\\config_DB.cnf";
                File cnf = new File(rutaArchivo);

                if(!cnf.exists()){
                    try {
                        cnf.createNewFile();
                    } catch (IOException ex) {
                        Logger.getLogger(Configuracion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                FileWriter fw;

                try {

                    fw = new FileWriter(cnf);
                    try (BufferedWriter bw = new BufferedWriter(fw)) {
                        PrintWriter salida = new PrintWriter(bw);
                        salida.write(confCifrada);

                    }
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Error al guardar configuración:\n" + e.getMessage(), "ERROR",
                        JOptionPane.ERROR_MESSAGE);
                }

                JOptionPane.showMessageDialog(null, "La configuración se guardó exitosamente!!", "CONFIGURACIÓN GUARDADA",
                            JOptionPane.INFORMATION_MESSAGE);

                this.dispose();
            }
        }
    }//GEN-LAST:event_btnGuardarDBActionPerformed

    private void btnRecargarConfigInternaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecargarConfigInternaMouseClicked
        // TODO add your handling code here:
        String li = "https://lh3.googleusercontent.com/sCG99HG8o51kkOnYc0sLjWEtVkyE3UqN19qNhRCzM8xRNzLh5C6wrKefrbMMKrHAxnhu6nz3LAAUOpjshesSz9ZvVIkLWr5Q18cNU049uz5Saza6mJAfUQfYZ5ODmf62U1rIt54Ujg=w2400";
        String ld = "http://lh3.googleusercontent.com/1vfHKJDGrMNsbsjRurXOpNtEzyez_Thp_pIHH7tTyFAilZaapN6Ca784rSRLyEsy5qmkJ8l9YedeqihjUpBB24nXSDm876vcZ-UyXqwoFtBvk4CPzs3HQ4tA_cFxsCnpiavNrOKLdw=w2400";
        
        this.txtUrlLogoIzq.setText(li);
        this.txtUrlLogoDer.setText(ld);
        
        this.mostrarPreview();
        
    }//GEN-LAST:event_btnRecargarConfigInternaMouseClicked

    private void mostrarPreview(){
        String urlLogoI = txtUrlLogoIzq.getText();
        String urlLogoD = txtUrlLogoDer.getText();

        //https://lh3.googleusercontent.com/sCG99HG8o51kkOnYc0sLjWEtVkyE3UqN19qNhRCzM8xRNzLh5C6wrKefrbMMKrHAxnhu6nz3LAAUOpjshesSz9ZvVIkLWr5Q18cNU049uz5Saza6mJAfUQfYZ5ODmf62U1rIt54Ujg=w2400
        //http://lh3.googleusercontent.com/1vfHKJDGrMNsbsjRurXOpNtEzyez_Thp_pIHH7tTyFAilZaapN6Ca784rSRLyEsy5qmkJ8l9YedeqihjUpBB24nXSDm876vcZ-UyXqwoFtBvk4CPzs3HQ4tA_cFxsCnpiavNrOKLdw=w2400
        String voucher_demo = "<html><head></head><body><div style=\"margin-top: 0px; font-family: arial; font-size: 8px;\">"
                + "<div>"
                + "<table border=\"0\" width=\"1\" cellspacing=\"1\" cellpadding=\"0\" style=\"width: 100%;\">"
                + "<tbody>"
                + "<tr>"
                + "<td>"
                + "<img width=\"40\" alt=\"Logo_izq\" src=\"" + urlLogoI + "\"/>"
                + "</td>"
                + "<td style=\"text-align: center; font-size: 6px;\">"
                + "<p><span style='font-size: 8px;'><b>ALCALDIA MUNICIPAL DEL DISTRITO CENTRAL</b></span><br><span style='font-size: 7px;'><b>GERENCIA DE RECURSOS HUMANOS</b></span><br><span style='font-size: 7px;'><b>DEPARTAMENTO DE PLANILLAS</b></span><br>Comprobante de Pago de MES" + " de AÑO" + "</p>"
                + "</td>"
                + "<td style = \"text-align: right;\">"
                + "<img width = \"40\" alt = \"Logo_der\" src=\"" + urlLogoD + "\"/>"
                + "</td>"
                + "</tr>"
                + "</tbody>"
                + "</table>"
                + "</div></body></html>";

        try {
            jTxtPane_logos.setText(voucher_demo);
        } catch (Exception e) {
        }
    }
    
    private void recuperarInformacion() {

        String ruta = "";
        File midir = new File(".");
        try {
            ruta = midir.getCanonicalPath();

        } catch (IOException e) {
        }

        String rutaArchivo = ruta + "\\src\\configuraciones\\config_DB.cnf";
        File cnf = new File(rutaArchivo);
        //Validar que el archivo existe
        if (!cnf.exists()) {

        } else {

            //validar que contiene parametros guardados
            FileReader fr;
            String texto;
            String textoCifrado = "";
            try {
                fr = new FileReader(rutaArchivo);

                BufferedReader br = new BufferedReader(fr);

                while ((texto = br.readLine()) != null) {
                    //System.out.println(texto);
                    textoCifrado = textoCifrado + texto;
                }
                
                fr.close();

            } catch (FileNotFoundException ex) {
                Logger.getLogger(Envio_Comprobantes_AMDC.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Envio_Comprobantes_AMDC.class.getName()).log(Level.SEVERE, null, ex);
            }

            TripleDes tDES = new TripleDes();

            String txtDecifrado = tDES.desEncriptar_txt_3DES(textoCifrado);

//            System.out.println(txtDecifrado);
            String datos[] = txtDecifrado.split("#&&#");
            
//            for (String dato : datos) {
//                System.out.println(dato);
//            }
            
            jTxtPane_logos.setContentType("text/html");
            this.txtURL.setText(datos[0]);
            this.txtPuerto.setText(datos[1]);
            this.txtBaseDatos.setText(datos[2]);
            this.txtUsuarioDB.setText(datos[3]);
            this.txtPassDB.setText(datos[4]);
            this.txtUrlLogoIzq.setText(datos[5]);
            this.txtUrlLogoDer.setText(datos[6]);
            
//            this.txtUrlLogoIzq.setMaximumSize(new java.awt.Dimension(6, 20));
            
            this.mostrarPreview();
            
//            this.urlLogoIzq = datos[5];
//            this.urlLogoDer = datos[6];

        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionInterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionInterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionInterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionInterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfiguracionInterna dialog = new ConfiguracionInterna(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarDB;
    private javax.swing.JButton btnProbarDB;
    private javax.swing.JLabel btnRecargarConfigInterna;
    private javax.swing.JButton btnSalirCnf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTxtPane_logos;
    private javax.swing.JTextField txtBaseDatos;
    private javax.swing.JPasswordField txtPassDB;
    private javax.swing.JTextField txtPuerto;
    private javax.swing.JTextField txtURL;
    private javax.swing.JTextField txtUrlLogoDer;
    private javax.swing.JTextField txtUrlLogoIzq;
    private javax.swing.JTextField txtUsuarioDB;
    // End of variables declaration//GEN-END:variables
}
