/*

 * @Nombre    : LogIn
 * @Author    : Erick Rodriguez
 * @Copyright : Erick Rodriguez
 * @Creado el : 14-ago-2017, 09:29:37 AM
 */
package envio_comprobantes_amdc;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick R. Rodriguez
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        //Visual_frame es el nombre del JFrame principal
        LogIn.this.setUndecorated(true);
        initComponents();
        //Con esto hacemos que el JFrame no se vea 
        //Sino puedes quitarlo.
        LogIn.this.setBackground(new Color(0, 0, 0, 0f));
        //Con esto le damos tranparencia a los objetos que tiene el JFrame
        //Tambien al JFrame, desde 0.0f a 1.0f 
        LogIn.this.setOpacity(0.94f);

        lblLogin.setBackground(new Color(0, 0, 0, 0.94f));
        if (txtPass.getText().equals("Contraseña")) {
            txtPass.setEchoChar((char) 0);
        }

        btnLogIn.setToolTipText("Iniciar sesión.");
        btnSalir.setToolTipText("Salir de la aplicación.");
        txtUsu.setToolTipText("Ingrese el nombre de usuario.");
        txtPass.setToolTipText("Ingrese la contraseña.");
        this.getRootPane().setDefaultButton(btnLogIn);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/login.png"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogIn = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtUsu = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesión");
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(623, 359));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogIn.setBackground(new java.awt.Color(49, 66, 82));
        btnLogIn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn.setText("Ingresar");
        btnLogIn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogIn.setOpaque(false);
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 110, 40));

        btnSalir.setBackground(new java.awt.Color(49, 66, 82));
        btnSalir.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setOpaque(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 100, 40));

        txtUsu.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtUsu.setForeground(new java.awt.Color(153, 153, 153));
        txtUsu.setText("Usuario");
        txtUsu.setBorder(null);
        txtUsu.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUsu.setOpaque(false);
        txtUsu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuFocusLost(evt);
            }
        });
        getContentPane().add(txtUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 230, 50));

        txtPass.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtPass.setForeground(new java.awt.Color(153, 153, 153));
        txtPass.setText("Contraseña");
        txtPass.setToolTipText("");
        txtPass.setBorder(null);
        txtPass.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPass.setOpaque(false);
        txtPass.setPreferredSize(new java.awt.Dimension(90, 35));
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login_frm.png"))); // NOI18N
        lblLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblLoginMouseDragged(evt);
            }
        });
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLoginMousePressed(evt);
            }
        });
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 600, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:

        String user = txtUsu.getText();
        String passV = txtPass.getText();
        char passR[] = txtPass.getPassword();
        
        if(txtUsu.getText().equals("Usuario")){
            user = "";
        }
        
        if(passV.equals("Contraseña")){
            passV = "";
        }

        if (user.length() == 0 || passR.length == 0 || passV.length() == 0) {
            JOptionPane.showMessageDialog(null, "Credenciales para iniciar sesión incompletas", "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        } else {

            MD5 md5 = new MD5();

            String pass = "";

            for (int i = 0; i < passR.length; i++) {
                pass += passR[i];
            }
            passR = null;

            String passMd5 = md5.obtenerHashMD5(pass);

            String passSha256 = md5.getSha256(passMd5, "@MdC_1m_@_2014");

            Con_DB db = new Con_DB();
            db.conectar();
            String rolPlanMensual = "5";
            if (db.autenticado(user, passSha256, "usuarios", "usuario", "pass")) {
                //Validar si tiene el permiso 

                ResultSet datos = db.ejecutarSELECT("SELECT r.* FROM usuarios AS u, roles AS r WHERE u.usuario ='" + user + "' "
                        + "AND u.pass = '" + passSha256 + "' "
                        + "AND r.id_rol = u.id_rol");

                try {
                    while (datos.next()) {
                        rolPlanMensual = datos.getString("plan_mensual");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
                }

                if (rolPlanMensual.equals("1")) {
                    mostrarPantallaPrincipal();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario no autorizado", "ERROR",
                            JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña son incorrectos", "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            }

            db.cierraConexion();
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void lblLoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseDragged
        // TODO add your handling code here:
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_lblLoginMouseDragged

    private void lblLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lblLoginMousePressed

    private void txtUsuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuFocusGained
        // TODO add your handling code here:
        String usu = txtUsu.getText().trim();
        if (usu.equals("Usuario")) {
            txtUsu.setText("");
            txtUsu.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_txtUsuFocusGained

    private void txtUsuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuFocusLost
        // TODO add your handling code here:
        String usu = txtUsu.getText().trim();
        if (usu.length() == 0) {
            txtUsu.setText("Usuario");
            txtUsu.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtUsuFocusLost

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        // TODO add your handling code here:
        String pass = txtPass.getText().trim();
        if (pass.equals("Contraseña")) {
            txtPass.setText("");
            txtPass.setEchoChar('*');
            txtPass.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_txtPassFocusGained

    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost
        // TODO add your handling code here:
        String pass = txtPass.getText().trim();
        if (pass.length() == 0) {
            txtPass.setText("Contraseña");
            txtPass.setForeground(new java.awt.Color(153, 153, 153));
            txtPass.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_txtPassFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    public static void mostrarPantallaPrincipal() {
        Principal f = new Principal();
        int w = 1100;//799;
        int h = 550;//411;
        f.setMinimumSize(new Dimension(w, h));
        f.setMaximumSize(new Dimension(w, h));
        f.setResizable(false);
        f.setTitle("V@UCHERS");

        //obtener el tamaño de la pantalla
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determinar la posición del inicio de pantalla
        int x = (dim.width - w - 40) / 2;//Ancho de pantalla menos ancho de ventana dividido entre 2
        int y = (dim.height - h - 80) / 2;//alto de pantalla menos alto de ventana dividido entre 2

        // Asignar la ventana
        f.setLocation(x, y);

        f.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsu;
    // End of variables declaration//GEN-END:variables

    private int x;
    private int y;

}
