/*

 * @Nombre    : Principal
 * @Author    : Erick Rodriguez
 * @Copyright : Erick Rodriguez
 * @Creado el : 14-ago-2017, 10:08:58 AM
 */
package envio_comprobantes_amdc;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Erick R. Rodriguez
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        hiloProcesos = new ThreadProcesos("llenarAnios");
        hiloProcesos.start();

        SpinnerNumberModel nm1 = new SpinnerNumberModel();
        nm1.setMaximum(100);
        nm1.setMinimum(1);
        nm1.setValue(95);

        SpinnerNumberModel nm2 = new SpinnerNumberModel();
        nm2.setMaximum(120);
        nm2.setMinimum(1);
        nm2.setValue(70);

        valMaxCorreos.setModel(nm1);
        tiempoEspera.setModel(nm2);

        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                if (enviando) {
                    Object[] opciones = {"Si", "No"};
                    int OP = JOptionPane.showOptionDialog(null, "Actualmente se encuentra enviando comprobantes\nDesea salir de la aplicación?", "Envío en curso", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[1]);

                    if (OP == 0) {
                        System.exit(0);
                    } else {

                    }
                } else {
                    System.exit(0);
                }
            }
        });
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/correo.png"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelCnf = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbAnio = new javax.swing.JComboBox<>();
        valMaxCorreos = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tiempoEspera = new javax.swing.JSpinner();
        chkAcuerdo = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        chkContratoPorHora = new javax.swing.JCheckBox();
        lblTitulo = new javax.swing.JLabel();
        pnlEnvios = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtVoucher = new javax.swing.JTextPane();
        lblCorreosDisponibles = new javax.swing.JLabel();
        pbrEnviados = new javax.swing.JProgressBar();
        lblPorcentaje = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTiempoTrancurrido = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pbrEnviadosCH = new javax.swing.JProgressBar();
        jLabel10 = new javax.swing.JLabel();
        lblTiempoTrancurridoCH = new javax.swing.JLabel();
        lblCorreosDisponiblesCH = new javax.swing.JLabel();
        lblPorcentajeCH = new javax.swing.JLabel();
        lblPlanillasEncontradasCH = new javax.swing.JLabel();
        barraTitulo = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnlEstado = new javax.swing.JPanel();
        pbrEnviosCiclo = new javax.swing.JProgressBar();
        lblEstado = new javax.swing.JLabel();
        mnuLateral = new javax.swing.JPanel();
        btnMnuConfig = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnMnuSalir = new javax.swing.JLabel();
        btnMnuInfo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnIniciarEnvio = new javax.swing.JButton();
        lblCuentaAtras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCnf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configuración de Envío", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14))); // NOI18N
        panelCnf.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Año");

        cmbAnio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cmbAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAnio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAnioItemStateChanged(evt);
            }
        });

        valMaxCorreos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        valMaxCorreos.setToolTipText("Máximo de comprobantes que se eniviarán antes de esperar.");
        valMaxCorreos.setValue(95);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Máximo por Envío");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Mes");

        cmbMes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMesItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Tiempo de Espera Entre Envíos (mins)");

        tiempoEspera.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tiempoEspera.setToolTipText("Tiempo en minutos de espera entre cada envío de comprobantes.");
        tiempoEspera.setValue(70);

        chkAcuerdo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        chkAcuerdo.setSelected(true);
        chkAcuerdo.setText("Acuerdo");
        chkAcuerdo.setToolTipText("Activar si desea enviar los comprobantes de empleados de acuerdo");
        chkAcuerdo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkAcuerdoItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Enviar comprobantes de:");

        chkContratoPorHora.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        chkContratoPorHora.setSelected(true);
        chkContratoPorHora.setText("Contrato por hora");
        chkContratoPorHora.setToolTipText("Activar si desea enviar los comprobantes de empleados de contrato por hora.");
        chkContratoPorHora.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkContratoPorHoraItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelCnfLayout = new javax.swing.GroupLayout(panelCnf);
        panelCnf.setLayout(panelCnfLayout);
        panelCnfLayout.setHorizontalGroup(
            panelCnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCnfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCnfLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCnfLayout.createSequentialGroup()
                        .addComponent(chkAcuerdo)
                        .addGap(18, 18, 18)
                        .addComponent(chkContratoPorHora)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCnfLayout.createSequentialGroup()
                        .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valMaxCorreos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tiempoEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCnfLayout.setVerticalGroup(
            panelCnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCnfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valMaxCorreos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempoEspera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAcuerdo)
                    .addComponent(jLabel8)
                    .addComponent(chkContratoPorHora))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelCnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 900, 100));

        lblTitulo.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Envío Automático de Comprobantes de Pago A.M.D.C.");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 910, -1));

        pnlEnvios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado de los Envíos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14))); // NOI18N
        pnlEnvios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Correos enviados de acuerdo");
        pnlEnvios.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 27));

        jScrollPane2.setBackground(new java.awt.Color(204, 153, 0));

        txtVoucher.setEditable(false);
        txtVoucher.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        txtVoucher.setFocusable(false);
        jScrollPane2.setViewportView(txtVoucher);

        pnlEnvios.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 94, 870, 220));

        lblCorreosDisponibles.setBackground(new java.awt.Color(255, 204, 255));
        lblCorreosDisponibles.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCorreosDisponibles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlEnvios.add(lblCorreosDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 90, 27));

        pbrEnviados.setForeground(new java.awt.Color(0, 255, 51));
        pnlEnvios.add(pbrEnviados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 193, 10));

        lblPorcentaje.setBackground(new java.awt.Color(255, 204, 204));
        lblPorcentaje.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblPorcentaje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlEnvios.add(lblPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 60, 26));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        jLabel7.setText("Tiempo transcurrido:");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlEnvios.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 23));

        lblTiempoTrancurrido.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        lblTiempoTrancurrido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTiempoTrancurrido.setText("00:00:00");
        lblTiempoTrancurrido.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlEnvios.add(lblTiempoTrancurrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 110, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Correos enviados de contrato");
        pnlEnvios.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        pbrEnviadosCH.setForeground(new java.awt.Color(0, 255, 51));
        pnlEnvios.add(pbrEnviadosCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 193, 10));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        jLabel10.setText("Tiempo transcurrido:");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlEnvios.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, 20));

        lblTiempoTrancurridoCH.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        lblTiempoTrancurridoCH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTiempoTrancurridoCH.setText("00:00:00");
        lblTiempoTrancurridoCH.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlEnvios.add(lblTiempoTrancurridoCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 110, -1));

        lblCorreosDisponiblesCH.setBackground(new java.awt.Color(255, 204, 255));
        lblCorreosDisponiblesCH.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCorreosDisponiblesCH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlEnvios.add(lblCorreosDisponiblesCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 90, 27));

        lblPorcentajeCH.setBackground(new java.awt.Color(255, 204, 204));
        lblPorcentajeCH.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblPorcentajeCH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlEnvios.add(lblPorcentajeCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 60, 26));

        lblPlanillasEncontradasCH.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPlanillasEncontradasCH.setText("Planillas encontradas");
        pnlEnvios.add(lblPlanillasEncontradasCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 179, -1));

        getContentPane().add(pnlEnvios, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 900, 330));

        barraTitulo.setBackground(new java.awt.Color(0, 118, 140));
        barraTitulo.setMaximumSize(new java.awt.Dimension(1100, 48));
        barraTitulo.setMinimumSize(new java.awt.Dimension(1100, 48));
        barraTitulo.setPreferredSize(new java.awt.Dimension(1100, 48));
        barraTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraTituloMouseDragged(evt);
            }
        });
        barraTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraTituloMousePressed(evt);
            }
        });

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        btnCerrar.setToolTipText("Salir del sistema");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimazar.png"))); // NOI18N
        jLabel11.setToolTipText("Minimizar");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Vouchers.png"))); // NOI18N
        jLabel12.setText("V@UCHERS");

        javax.swing.GroupLayout barraTituloLayout = new javax.swing.GroupLayout(barraTitulo);
        barraTitulo.setLayout(barraTituloLayout);
        barraTituloLayout.setHorizontalGroup(
            barraTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraTituloLayout.createSequentialGroup()
                .addContainerGap(431, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(380, 380, 380)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addContainerGap())
        );
        barraTituloLayout.setVerticalGroup(
            barraTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraTituloLayout.createSequentialGroup()
                .addGroup(barraTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(barraTituloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(barraTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(btnCerrar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(barraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1109, -1));

        pnlEstado.setBackground(new java.awt.Color(0, 118, 140));
        pnlEstado.setForeground(new java.awt.Color(204, 204, 204));

        pbrEnviosCiclo.setBackground(new java.awt.Color(0, 118, 140));
        pbrEnviosCiclo.setForeground(new java.awt.Color(255, 102, 0));
        pbrEnviosCiclo.setFocusable(false);
        pbrEnviosCiclo.setMaximumSize(new java.awt.Dimension(1082, 6));
        pbrEnviosCiclo.setMinimumSize(new java.awt.Dimension(1082, 6));
        pbrEnviosCiclo.setPreferredSize(new java.awt.Dimension(1050, 6));

        lblEstado.setBackground(new java.awt.Color(255, 255, 255));
        lblEstado.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout pnlEstadoLayout = new javax.swing.GroupLayout(pnlEstado);
        pnlEstado.setLayout(pnlEstadoLayout);
        pnlEstadoLayout.setHorizontalGroup(
            pnlEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbrEnviosCiclo, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlEstadoLayout.setVerticalGroup(
            pnlEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadoLayout.createSequentialGroup()
                .addComponent(pbrEnviosCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 1110, 50));

        mnuLateral.setBackground(new java.awt.Color(49, 66, 82));
        mnuLateral.setMaximumSize(new java.awt.Dimension(190, 620));
        mnuLateral.setMinimumSize(new java.awt.Dimension(190, 620));
        mnuLateral.setPreferredSize(new java.awt.Dimension(190, 620));

        btnMnuConfig.setBackground(new java.awt.Color(49, 66, 82));
        btnMnuConfig.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnMnuConfig.setForeground(new java.awt.Color(204, 204, 204));
        btnMnuConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/img_conf.png"))); // NOI18N
        btnMnuConfig.setText("Configuración");
        btnMnuConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMnuConfig.setOpaque(true);
        btnMnuConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMnuConfigMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMnuConfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMnuConfigMouseExited(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoAMDC3_3.5.png"))); // NOI18N

        btnMnuSalir.setBackground(new java.awt.Color(49, 66, 82));
        btnMnuSalir.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnMnuSalir.setForeground(new java.awt.Color(204, 204, 204));
        btnMnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/apagar.png"))); // NOI18N
        btnMnuSalir.setText("Salir");
        btnMnuSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMnuSalir.setOpaque(true);
        btnMnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMnuSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMnuSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMnuSalirMouseExited(evt);
            }
        });

        btnMnuInfo.setBackground(new java.awt.Color(49, 66, 82));
        btnMnuInfo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnMnuInfo.setForeground(new java.awt.Color(204, 204, 204));
        btnMnuInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono-info.png"))); // NOI18N
        btnMnuInfo.setText("Acerca de...");
        btnMnuInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMnuInfo.setOpaque(true);
        btnMnuInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMnuInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMnuInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMnuInfoMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Vouchers.png"))); // NOI18N

        javax.swing.GroupLayout mnuLateralLayout = new javax.swing.GroupLayout(mnuLateral);
        mnuLateral.setLayout(mnuLateralLayout);
        mnuLateralLayout.setHorizontalGroup(
            mnuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMnuConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addComponent(btnMnuSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMnuInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mnuLateralLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mnuLateralLayout.setVerticalGroup(
            mnuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnuLateralLayout.createSequentialGroup()
                .addGroup(mnuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mnuLateralLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(mnuLateralLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                .addComponent(btnMnuConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMnuInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMnuSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(mnuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 580));

        btnIniciarEnvio.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnIniciarEnvio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/envio_comprobantes_amdc/green-mail-send-icon.png"))); // NOI18N
        btnIniciarEnvio.setText("Iniciar Envío");
        btnIniciarEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarEnvioActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, -1, 40));

        lblContinuara.setBackground(new java.awt.Color(255, 204, 255));
        lblContinuara.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblContinuara.setForeground(new java.awt.Color(0, 51, 255));
        lblContinuara.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblContinuara, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 138, 40));

        lblCuentaAtras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCuentaAtras.setForeground(new java.awt.Color(0, 51, 255));
        lblCuentaAtras.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblCuentaAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 100, 26));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAnioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAnioItemStateChanged
        // TODO add your handling code here:
        if (cargado) {
            cargado = false;
            
            hiloProcesos = new ThreadProcesos("llenarMeses");
            hiloProcesos.start();

        }
    }//GEN-LAST:event_cmbAnioItemStateChanged

    private void cmbMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMesItemStateChanged
        // TODO add your handling code here:
        if (cargado) {
            if (chkAcuerdo.isSelected()) {
                hiloProcesos = new ThreadProcesos("getCorreosDiponibles");
                hiloProcesos.start();
            }
            
            if (chkContratoPorHora.isSelected()) {
                hiloProcesos = new ThreadProcesos("getCorreosDiponiblesCH");
                hiloProcesos.start();
            }
        }
    }//GEN-LAST:event_cmbMesItemStateChanged

    private void btnIniciarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarEnvioActionPerformed
        // TODO add your handling code here:

        boolean ac = chkAcuerdo.isSelected();
        boolean ch = chkContratoPorHora.isSelected();

        if (ac || ch) {

            Object[] opciones = {"Si", "No"};
            int OP = JOptionPane.showOptionDialog(null, "Desea iniciar el envío de comprobantes?", "Confirmación", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

            if (OP == 0) {
                hiloProcesos = new ThreadProcesos("iniciarEnvio");
                hiloProcesos.start();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar al menos un tipo de comprobantes para ser enviados", "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIniciarEnvioActionPerformed

    private void chkAcuerdoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkAcuerdoItemStateChanged
        // TODO add your handling code here:
        if (chkAcuerdo.isSelected()) {
            hiloProcesos = new ThreadProcesos("getCorreosDiponibles");
            hiloProcesos.start();
        } else {
            lblCorreosDisponibles.setText("");
            lblPorcentaje.setText("");
        }
    }//GEN-LAST:event_chkAcuerdoItemStateChanged

    private void chkContratoPorHoraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkContratoPorHoraItemStateChanged
        // TODO add your handling code here:
        if (chkContratoPorHora.isSelected()) {
            lblPlanillasEncontradasCH.setText("Cargando..");
            hiloProcesos = new ThreadProcesos("getCorreosDiponiblesCH");
            hiloProcesos.start();
        } else {
            lblCorreosDisponiblesCH.setText("");
            lblPorcentajeCH.setText("");
            lblPlanillasEncontradasCH.setText("Planillas encontradas 0");
        }
    }//GEN-LAST:event_chkContratoPorHoraItemStateChanged

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void barraTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraTituloMouseDragged
        // TODO add your handling code here:
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - xf, point.y - yf);
    }//GEN-LAST:event_barraTituloMouseDragged

    private void barraTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraTituloMousePressed
        // TODO add your handling code here:
        xf = evt.getX();
        yf = evt.getY();
    }//GEN-LAST:event_barraTituloMousePressed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(Principal.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void btnMnuConfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMnuConfigMouseEntered
        // TODO add your handling code here:
        btnMnuConfig.setBackground(new java.awt.Color(0, 118, 140));
    }//GEN-LAST:event_btnMnuConfigMouseEntered

    private void btnMnuConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMnuConfigMouseExited
        // TODO add your handling code here:
        btnMnuConfig.setBackground(new java.awt.Color(49,66,82));
    }//GEN-LAST:event_btnMnuConfigMouseExited

    private void btnMnuSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMnuSalirMouseEntered
        // TODO add your handling code here:
        btnMnuSalir.setBackground(new java.awt.Color(0, 118, 140));
    }//GEN-LAST:event_btnMnuSalirMouseEntered

    private void btnMnuSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMnuSalirMouseExited
        // TODO add your handling code here:
        btnMnuSalir.setBackground(new java.awt.Color(49,66,82));
    }//GEN-LAST:event_btnMnuSalirMouseExited

    private void btnMnuInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMnuInfoMouseEntered
        // TODO add your handling code here:
        btnMnuInfo.setBackground(new java.awt.Color(0, 118, 140));
    }//GEN-LAST:event_btnMnuInfoMouseEntered

    private void btnMnuInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMnuInfoMouseExited
        // TODO add your handling code here:
        btnMnuInfo.setBackground(new java.awt.Color(49,66,82));
    }//GEN-LAST:event_btnMnuInfoMouseExited

    private void btnMnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMnuSalirMouseClicked
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_btnMnuSalirMouseClicked

    private void btnMnuInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMnuInfoMouseClicked
        // TODO add your handling code here:
        mostrarAcercaDe();
    }//GEN-LAST:event_btnMnuInfoMouseClicked

    private void btnMnuConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMnuConfigMouseClicked
        // TODO add your handling code here:
        mostrarConfiguracion();
    }//GEN-LAST:event_btnMnuConfigMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private void salir() {
        if (enviando) {
            Object[] opciones = {"Si", "No"};
            int OP = JOptionPane.showOptionDialog(null, "Actualmente se encuentra enviando comprobantes\nDesea salir de la aplicación?", "Envío en curso", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[1]);

            if (OP == 0) {
                System.exit(0);
            }
        } else {
            System.exit(0);
        }
    }
    
    public void mostrarConfiguracion() {
        ConfiguracionInterna f = new ConfiguracionInterna(this, true);
        int w = 476;
        int h = 620;
        f.setMinimumSize(new Dimension(w, h));
        f.setMaximumSize(new Dimension(w, h));
        f.setResizable(false);
        f.setTitle("Configuración de Conexión y Logos");
        
        //obtener el tamaño de la pantalla
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determinar la posición del inicio de pantalla
        int x = (dim.width - w - 30) / 2;//Ancho de pantalla menos ancho de ventana dividido entre 2
        int y = (dim.height - h - 80) / 2;//alto de pantalla menos alto de ventana dividido entre 2

        // Asignar la ventana
        f.setLocation(x, y);

        f.setVisible(true);
    }
    
    public void mostrarAcercaDe() {
        AcercaDe f = new AcercaDe(this);
        int w = 452;
        int h = 214;
        f.setMinimumSize(new Dimension(w, h));
        f.setMaximumSize(new Dimension(w, h));
        f.setResizable(false);
        f.setTitle("Acerca De ...");
        
        //obtener el tamaño de la pantalla
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determinar la posición del inicio de pantalla
        int x = (dim.width - w) / 2;//Ancho de pantalla menos ancho de ventana dividido entre 2
        int y = (dim.height - h) / 2;//alto de pantalla menos alto de ventana dividido entre 2

        // Asignar la ventana
        f.setLocation(x, y);

        //f.setAlwaysOnTop(true);
        this.setEnabled(false);
//        try {
//            f.getRootPane().setOpaque(false);
//            f.getContentPane().setBackground(new Color(0, 0, 0, 0));
//            //f.setBackground(new Color(0, 0, 0, 0));
//        } catch (Exception e) {
//        }
        f.setVisible(true);
        //this.setEnabled(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraTitulo;
    private javax.swing.JLabel btnCerrar;
    public static javax.swing.JButton btnIniciarEnvio;
    private javax.swing.JLabel btnMnuConfig;
    private javax.swing.JLabel btnMnuInfo;
    private javax.swing.JLabel btnMnuSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JCheckBox chkAcuerdo;
    public static javax.swing.JCheckBox chkContratoPorHora;
    public static javax.swing.JComboBox<String> cmbAnio;
    public static javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    public static final javax.swing.JLabel lblContinuara = new javax.swing.JLabel();
    public static javax.swing.JLabel lblCorreosDisponibles;
    public static javax.swing.JLabel lblCorreosDisponiblesCH;
    public static javax.swing.JLabel lblCuentaAtras;
    public static javax.swing.JLabel lblEstado;
    public static javax.swing.JLabel lblPlanillasEncontradasCH;
    public static javax.swing.JLabel lblPorcentaje;
    public static javax.swing.JLabel lblPorcentajeCH;
    public static javax.swing.JLabel lblTiempoTrancurrido;
    public static javax.swing.JLabel lblTiempoTrancurridoCH;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel mnuLateral;
    private javax.swing.JPanel panelCnf;
    public static javax.swing.JProgressBar pbrEnviados;
    public static javax.swing.JProgressBar pbrEnviadosCH;
    public static javax.swing.JProgressBar pbrEnviosCiclo;
    private javax.swing.JPanel pnlEnvios;
    private javax.swing.JPanel pnlEstado;
    public static javax.swing.JSpinner tiempoEspera;
    public static javax.swing.JTextPane txtVoucher;
    public static javax.swing.JSpinner valMaxCorreos;
    // End of variables declaration//GEN-END:variables

    public static boolean cargado = false;
    static Thread hiloProcesos = null;
    public static ThreadProcesos P = null;
    
    private int xf;
    private int yf;

    public static boolean enviando = false;
}
