/*

 * @Nombre    : Principal
 * @Author    : Erick Rodriguez
 * @Copyright : Erick Rodriguez
 * @Creado el : 14-ago-2017, 10:08:58 AM
 */
package envio_comprobantes_amdc;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Erick R. Rodriguez
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        hiloProcesos = new ThreadProcesos("llenarAnios");
        hiloProcesos.start();

        SpinnerNumberModel nm1 = new SpinnerNumberModel();
        nm1.setMaximum(100);
        nm1.setMinimum(1);
        nm1.setValue(95);

        SpinnerNumberModel nm2 = new SpinnerNumberModel();
        nm2.setMaximum(120);
        nm2.setMinimum(1);
        nm2.setValue(70);

        valMaxCorreos.setModel(nm1);
        tiempoEspera.setModel(nm2);

        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                if (enviando) {
                    Object[] opciones = {"Si", "No"};
                    int OP = JOptionPane.showOptionDialog(null, "Actualmente se encuentra enviando comprobantes\nDesea salir de la aplicación?", "Envío en curso", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[1]);

                    if (OP == 0) {
                        System.exit(0);
                    } else {

                    }
                } else {
                    System.exit(0);
                }
            }
        });
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/correo.png"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelCnf = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbAnio = new javax.swing.JComboBox<>();
        valMaxCorreos = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tiempoEspera = new javax.swing.JSpinner();
        chkAcuerdo = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        chkContratoPorHora = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblCorreosDisponibles = new javax.swing.JLabel();
        pbrEnviados = new javax.swing.JProgressBar();
        lblPorcentaje = new javax.swing.JLabel();
        btnIniciarEnvio = new javax.swing.JButton();
        lblCuentaAtras = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTiempoTrancurrido = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtVoucher = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        pbrEnviadosCH = new javax.swing.JProgressBar();
        jLabel10 = new javax.swing.JLabel();
        lblTiempoTrancurridoCH = new javax.swing.JLabel();
        lblCorreosDisponiblesCH = new javax.swing.JLabel();
        lblPorcentajeCH = new javax.swing.JLabel();
        lblPlanillasEncontradasCH = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        pbrEnviosCiclo = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuConfiguracion = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuAcercade = new javax.swing.JMenu();
        mnuAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(getIconImage());

        panelCnf.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuración de Envío"));

        jLabel2.setText("Año");

        cmbAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAnio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAnioItemStateChanged(evt);
            }
        });

        valMaxCorreos.setToolTipText("Máximo de comprobantes que se eniviarán antes de esperar.");
        valMaxCorreos.setValue(95);

        jLabel3.setText("Máximo por Envío");

        jLabel4.setText("Mes");

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMesItemStateChanged(evt);
            }
        });

        jLabel6.setText("Tiempo de Espera Entre Envíos (mins)");

        tiempoEspera.setToolTipText("Tiempo en minutos de espera entre cada envío de comprobantes.");
        tiempoEspera.setValue(70);

        chkAcuerdo.setSelected(true);
        chkAcuerdo.setText("Acuerdo");
        chkAcuerdo.setToolTipText("Activar si desea enviar los comprobantes de empleados de acuerdo");
        chkAcuerdo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkAcuerdoItemStateChanged(evt);
            }
        });

        jLabel8.setText("Enviar comprobantes de:");

        chkContratoPorHora.setSelected(true);
        chkContratoPorHora.setText("Contrato por hora");
        chkContratoPorHora.setToolTipText("Activar si desea enviar los comprobantes de empleados de contrato por hora.");
        chkContratoPorHora.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkContratoPorHoraItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelCnfLayout = new javax.swing.GroupLayout(panelCnf);
        panelCnf.setLayout(panelCnfLayout);
        panelCnfLayout.setHorizontalGroup(
            panelCnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCnfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCnfLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCnfLayout.createSequentialGroup()
                        .addComponent(chkAcuerdo)
                        .addGap(18, 18, 18)
                        .addComponent(chkContratoPorHora)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCnfLayout.createSequentialGroup()
                        .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valMaxCorreos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tiempoEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCnfLayout.setVerticalGroup(
            panelCnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCnfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valMaxCorreos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tiempoEspera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAcuerdo)
                    .addComponent(jLabel8)
                    .addComponent(chkContratoPorHora))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Envío Automático de Comprobantes de Pago A.M.D.C.");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado de los Envíos"));

        jLabel5.setText("Correos enviados de acuerdo");

        lblCorreosDisponibles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreosDisponibles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        pbrEnviados.setForeground(new java.awt.Color(0, 255, 51));

        lblPorcentaje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnIniciarEnvio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIniciarEnvio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/envio_comprobantes_amdc/green-mail-send-icon.png"))); // NOI18N
        btnIniciarEnvio.setText("Iniciar Envío");
        btnIniciarEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarEnvioActionPerformed(evt);
            }
        });

        lblCuentaAtras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCuentaAtras.setForeground(new java.awt.Color(0, 51, 255));
        lblCuentaAtras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCuentaAtras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblContinuara.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblContinuara.setForeground(new java.awt.Color(0, 51, 255));
        lblContinuara.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContinuara.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel7.setText("Tiempo transcurrido:");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblTiempoTrancurrido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTiempoTrancurrido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTiempoTrancurrido.setText("00:00:00");
        lblTiempoTrancurrido.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtVoucher.setEditable(false);
        txtVoucher.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        txtVoucher.setFocusable(false);
        jScrollPane2.setViewportView(txtVoucher);

        jLabel9.setText("Correos enviados de contrato");

        pbrEnviadosCH.setForeground(new java.awt.Color(0, 255, 51));

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel10.setText("Tiempo transcurrido:");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblTiempoTrancurridoCH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTiempoTrancurridoCH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTiempoTrancurridoCH.setText("00:00:00");
        lblTiempoTrancurridoCH.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblCorreosDisponiblesCH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreosDisponiblesCH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblPorcentajeCH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblPlanillasEncontradasCH.setText("Planillas encontradas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTiempoTrancurrido, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pbrEnviados, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCorreosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTiempoTrancurridoCH, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pbrEnviadosCH, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPorcentajeCH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCorreosDisponiblesCH, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPlanillasEncontradasCH, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIniciarEnvio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblContinuara, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCuentaAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pbrEnviados, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblTiempoTrancurrido)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCorreosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblCuentaAtras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblContinuara, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(btnIniciarEnvio))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPorcentajeCH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCorreosDisponiblesCH, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(lblPlanillasEncontradasCH))
                                .addGap(57, 57, 57))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(pbrEnviadosCH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTiempoTrancurridoCH))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEstado.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/envio_comprobantes_amdc/salir-de-mi-perfil-icono-3964-32.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        pbrEnviosCiclo.setForeground(new java.awt.Color(255, 102, 0));
        pbrEnviosCiclo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        mnuConfiguracion.setText("Archivo");
        mnuConfiguracion.setToolTipText("");
        mnuConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConfiguracionActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuration_config_system_1540.png"))); // NOI18N
        jMenuItem1.setText("Configuración");
        jMenuItem1.setActionCommand("Configuracion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuConfiguracion.add(jMenuItem1);
        mnuConfiguracion.add(jSeparator1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/envio_comprobantes_amdc/salir-de-mi-perfil-icono-3964-32.png"))); // NOI18N
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuConfiguracion.add(jMenuItem2);

        jMenuBar1.add(mnuConfiguracion);

        mnuAcercade.setText("Acerca de...");
        mnuAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcercadeActionPerformed(evt);
            }
        });

        mnuAcercaDe.setText("Acerca de ...");
        mnuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcercaDeActionPerformed(evt);
            }
        });
        mnuAcercade.add(mnuAcercaDe);

        jMenuBar1.add(mnuAcercade);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCnf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbrEnviosCiclo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(panelCnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbrEnviosCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAnioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAnioItemStateChanged
        // TODO add your handling code here:
        if (cargado) {
            cargado = false;
            
            hiloProcesos = new ThreadProcesos("llenarMeses");
            hiloProcesos.start();

        }
    }//GEN-LAST:event_cmbAnioItemStateChanged

    private void cmbMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMesItemStateChanged
        // TODO add your handling code here:
        if (cargado) {
            if (chkAcuerdo.isSelected()) {
                hiloProcesos = new ThreadProcesos("getCorreosDiponibles");
                hiloProcesos.start();
            }
            
            if (chkContratoPorHora.isSelected()) {
                hiloProcesos = new ThreadProcesos("getCorreosDiponiblesCH");
                hiloProcesos.start();
            }
        }
    }//GEN-LAST:event_cmbMesItemStateChanged

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.salir();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIniciarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarEnvioActionPerformed
        // TODO add your handling code here:

        boolean ac = chkAcuerdo.isSelected();
        boolean ch = chkContratoPorHora.isSelected();

        if (ac || ch) {

            Object[] opciones = {"Si", "No"};
            int OP = JOptionPane.showOptionDialog(null, "Desea iniciar el envío de comprobantes?", "Confirmación", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

            if (OP == 0) {
                hiloProcesos = new ThreadProcesos("iniciarEnvio");
                hiloProcesos.start();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar al menos un tipo de comprobantes para ser enviados", "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIniciarEnvioActionPerformed

    private void chkAcuerdoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkAcuerdoItemStateChanged
        // TODO add your handling code here:
        if (chkAcuerdo.isSelected()) {
            hiloProcesos = new ThreadProcesos("getCorreosDiponibles");
            hiloProcesos.start();
        } else {
            lblCorreosDisponibles.setText("");
            lblPorcentaje.setText("");
        }
    }//GEN-LAST:event_chkAcuerdoItemStateChanged

    private void chkContratoPorHoraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkContratoPorHoraItemStateChanged
        // TODO add your handling code here:
        if (chkContratoPorHora.isSelected()) {
            lblPlanillasEncontradasCH.setText("Cargando..");
            hiloProcesos = new ThreadProcesos("getCorreosDiponiblesCH");
            hiloProcesos.start();
        } else {
            lblCorreosDisponiblesCH.setText("");
            lblPorcentajeCH.setText("");
            lblPlanillasEncontradasCH.setText("Planillas encontradas 0");
        }
    }//GEN-LAST:event_chkContratoPorHoraItemStateChanged

    private void mnuAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcercadeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuAcercadeActionPerformed

    private void mnuConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConfiguracionActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_mnuConfiguracionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        mostrarConfiguracion();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcercaDeActionPerformed
        // TODO add your handling code here:
        mostrarAcercaDe();
    }//GEN-LAST:event_mnuAcercaDeActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private void salir() {
        if (enviando) {
            Object[] opciones = {"Si", "No"};
            int OP = JOptionPane.showOptionDialog(null, "Actualmente se encuentra enviando comprobantes\nDesea salir de la aplicación?", "Envío en curso", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[1]);

            if (OP == 0) {
                System.exit(0);
            }
        } else {
            System.exit(0);
        }
    }
    
    public void mostrarConfiguracion() {
        ConfiguracionInterna f = new ConfiguracionInterna(this, true);
        int w = 476;
        int h = 620;
        f.setMinimumSize(new Dimension(w, h));
        f.setMaximumSize(new Dimension(w, h));
        f.setResizable(false);
        f.setTitle("Configuración de Conexión y Logos");
        
        //obtener el tamaño de la pantalla
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determinar la posición del inicio de pantalla
        int x = (dim.width - w - 30) / 2;//Ancho de pantalla menos ancho de ventana dividido entre 2
        int y = (dim.height - h - 80) / 2;//alto de pantalla menos alto de ventana dividido entre 2

        // Asignar la ventana
        f.setLocation(x, y);

        f.setVisible(true);
    }
    
    public void mostrarAcercaDe() {
        AcercaDe f = new AcercaDe(this);
        int w = 452;
        int h = 214;
        f.setMinimumSize(new Dimension(w, h));
        f.setMaximumSize(new Dimension(w, h));
        f.setResizable(false);
        f.setTitle("Acerca De ...");
        
        //obtener el tamaño de la pantalla
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determinar la posición del inicio de pantalla
        int x = (dim.width - w) / 2;//Ancho de pantalla menos ancho de ventana dividido entre 2
        int y = (dim.height - h) / 2;//alto de pantalla menos alto de ventana dividido entre 2

        // Asignar la ventana
        f.setLocation(x, y);

        //f.setAlwaysOnTop(true);
        this.setEnabled(false);
//        try {
//            f.getRootPane().setOpaque(false);
//            f.getContentPane().setBackground(new Color(0, 0, 0, 0));
//            //f.setBackground(new Color(0, 0, 0, 0));
//        } catch (Exception e) {
//        }
        f.setVisible(true);
        //this.setEnabled(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnIniciarEnvio;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JCheckBox chkAcuerdo;
    public static javax.swing.JCheckBox chkContratoPorHora;
    public static javax.swing.JComboBox<String> cmbAnio;
    public static javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public static final javax.swing.JLabel lblContinuara = new javax.swing.JLabel();
    public static javax.swing.JLabel lblCorreosDisponibles;
    public static javax.swing.JLabel lblCorreosDisponiblesCH;
    public static javax.swing.JLabel lblCuentaAtras;
    public static javax.swing.JLabel lblEstado;
    public static javax.swing.JLabel lblPlanillasEncontradasCH;
    public static javax.swing.JLabel lblPorcentaje;
    public static javax.swing.JLabel lblPorcentajeCH;
    public static javax.swing.JLabel lblTiempoTrancurrido;
    public static javax.swing.JLabel lblTiempoTrancurridoCH;
    private javax.swing.JMenuItem mnuAcercaDe;
    private javax.swing.JMenu mnuAcercade;
    private javax.swing.JMenu mnuConfiguracion;
    private javax.swing.JPanel panelCnf;
    public static javax.swing.JProgressBar pbrEnviados;
    public static javax.swing.JProgressBar pbrEnviadosCH;
    public static javax.swing.JProgressBar pbrEnviosCiclo;
    public static javax.swing.JSpinner tiempoEspera;
    public static javax.swing.JTextPane txtVoucher;
    public static javax.swing.JSpinner valMaxCorreos;
    // End of variables declaration//GEN-END:variables

    public static boolean cargado = false;
    static Thread hiloProcesos = null;
    public static ThreadProcesos P = null;

    public static boolean enviando = false;
}
