/*

 * @Nombre    : Splash
 * @Author    : Erick Rodriguez
 * @Copyright : Erick Rodriguez
 * @Creado el : 09-mar-2019, 01:42:12 AM
 */
package envio_comprobantes_amdc;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Erick R. Rodríguez
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public Splash() {
        //initComponents();
        
        //Visual_frame es el nombre del JFrame principal
        Splash.this.setUndecorated(true);
        initComponents();
        //Con esto hacemos que el JFrame no se vea 
        //Sino puedes quitarlo.
        Splash.this.setBackground(new Color(0, 0, 0, 0));
        //Con esto le damos tranparencia a los objetos que tiene el JFrame
        //Tambien al JFrame, desde 0.0f a 1.0f 
        Splash.this.setOpacity(0.92f);

        lblImgSplash.setBackground(new Color(0, 0, 0, 0));

        llenarBarra();
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/correo.png"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBar_inicio = new javax.swing.JProgressBar();
        lblImgSplash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciando...");
        setIconImage(getIconImage());
        getContentPane().setLayout(null);

        pBar_inicio.setBackground(new java.awt.Color(49, 66, 82));
        pBar_inicio.setForeground(new java.awt.Color(255, 153, 0));
        pBar_inicio.setValue(10);
        pBar_inicio.setBorderPainted(false);
        pBar_inicio.setOpaque(true);
        getContentPane().add(pBar_inicio);
        pBar_inicio.setBounds(120, 360, 380, 6);

        lblImgSplash.setBackground(new java.awt.Color(102, 102, 102));
        lblImgSplash.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblImgSplash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Splash_Vouchers_hex_v334.png"))); // NOI18N
        lblImgSplash.setMaximumSize(new java.awt.Dimension(610, 480));
        lblImgSplash.setMinimumSize(new java.awt.Dimension(610, 480));
        lblImgSplash.setOpaque(true);
        lblImgSplash.setPreferredSize(new java.awt.Dimension(610, 480));
        lblImgSplash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgSplashMouseClicked(evt);
            }
        });
        getContentPane().add(lblImgSplash);
        lblImgSplash.setBounds(0, 0, 610, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblImgSplashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgSplashMouseClicked
        // TODO add your handling code here:
//        dispose();
//        mostrarLogIn();
    }//GEN-LAST:event_lblImgSplashMouseClicked

    public static void mostrarLogIn() {
        LogIn f = new LogIn();
        int w = 400;
        int h = 182;
        f.setMinimumSize(new Dimension(w, h));
        f.setMaximumSize(new Dimension(w, h));
        f.setResizable(false);
        f.setTitle("Inicio de Sesión");

        //obtener el tamaño de la pantalla
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determinar la posición del inicio de pantalla
        int x = (dim.width - w) / 2;//Ancho de pantalla menos ancho de ventana dividido entre 2
        int y = (dim.height - h) / 2;//alto de pantalla menos alto de ventana dividido entre 2

        // Asignar la ventana
        f.setLocation(x, y);

        f.setVisible(true);
    }

    public static void llenarBarra() 
    { 
        int i = 0; 
        try { 
            while (i <= 100) { 
                // fill the menu bar 
                pBar_inicio.setValue(i); 
  
                // delay the thread 
                Thread.sleep(100); 
                i += 5; 
            } 
        } 
        catch (Exception e) { 
        } 
    } 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImgSplash;
    private static javax.swing.JProgressBar pBar_inicio;
    // End of variables declaration//GEN-END:variables
}
